### PR TITLE
added session_factory_class to AIOHttpConnection

### PR DESCRIPTION
**Pull request by pgtuk**
## What do these changes do?

Added optional parameter `session_factory_class` to AIOHttpConnection, which allows creating custom session per connection.

## Are there changes in behavior for the user?

Optional parameter `session_factory_class` for AIOHttpConnection class.

## Checklist

- [x] I think the code is well written
- [x] Unit tests for the changes exist
- [ ] Documentation reflects the changes
- [ ] Add a new news fragment into the `CHANGES` folder
  * name it `<issue_id>.<type>` (e.g. `588.bugfix`)
  * if you don't have an `issue_id` change it to the pr id after creating the PR
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example: `Fix issue with non-ascii contents in doctest text files.`

### CODE REVIEW

**Comment by asvetlov** [comment]
I have 2 comments.
1. Why `SessionFactory` is a class? A simple function should be enough IMHO. At least the code just calls `session = session_factory(...)`.
2. `session` and `session_factory` should be mutually exclusive arguments, passing both is misleading.

Minor: if the session factory is not a class actually the argument name can be shortened to `session_factory`.

**Comment by pgtuk** [comment]
@asvetlov , `session` argument was left for backwards compatibility and maybe it would be better just to remove it at all.

**Comment by asvetlov** [comment]
The backward compatibility matters, please keep the `session` argument even if it is not used by your particular project.
A check for mutual exclusion is still desired.

**Comment by pgtuk** [comment]
Added assertion check for mutual exclusion of `session` and `session_factory`

**Comment by pgtuk** [comment]
@asvetlov any updates?

**Pull request merged**
