### PR TITLE
use async context manager instead of await to be compatible with more versions of aiohttp

### PR DESCRIPTION
**Pull request by vangheem**

### CODE REVIEW

**Comment by asvetlov** [comment]
Sorry for the late reply but what compatibility are you talking about?

**Comment by vangheem** [comment]
aiohttp response objects are context managers.

In older versions of aiohttp, the context managers were built in a way to be compatible with older versions of python along with new.

However, that also means that if you don't use the response object properly as a context manager, it throws an error.

We should use this like a context manager even if we don't care about being compatible with older versions of aiohttp.

**Comment by asvetlov** [comment]
> aiohttp response objects are context managers.

Really? 

> if you don't use the response object properly as a context manager, it throws an error.

Are you sure?

**Comment by vangheem** [comment]
See: https://github.com/aio-libs/aiohttp/blob/master/aiohttp/client.py#L220

Yes, this is the error I get when not using my branch:

```
TypeError: cannot 'yield from' a coroutine object in a non-coroutine generator
~``

**Comment by asvetlov** [comment]
Replace `yield from` with `await`

**Comment by vangheem** [comment]
I am using await. It is the version of aiohttp that is not.

**Comment by vangheem** [comment]
nonetheless, it is a context manager and should be used as one.

All the aiohttp docs say to use it as a context manager.

Otherwise, the responses will not get closed.

**Comment by asvetlov** [comment]
Your change is more idiomatic, sure.
But the current code is 100% correct.

**Comment by vangheem** [comment]
It's great that the current code works fine! I'm just trying to make it work for me :)

It fixes this package to work on older versions(2.x) of aiohttp and explicitly releases the response objects.

Any reason it shouldn't be merged?

**Comment by asvetlov** [comment]
I'm ok to merge but want to figure out what code doesn't work for you.
Do you mock aiohttp client?

**Comment by hellysmile** [comment]
Thanks for update! Sorry for very late merge...

**Pull request merged**
